siteTitle = "Blog by Jonathan Islas"
siteDescr = "A personal blog to talk about my ideas, problems and solutions. I'm a Web Developer btw."
siteAuthor = "Jonathan Islas"

siteTelegramUrl = "https://telegram.me/islas27"
siteTwitterUrl = "https://twitter.com/islas_27"
siteGithubUrl = "https://github.com/islas27"
siteBitbucketUrl = "https://bitbucket.com/islas27"
siteEmailUrl = "mailto:islasjonathan27@gmail.com"

googleAnalyticsId = "UA-92212026-1"

currentLocation = "Chihuahua, MX"

linkPrefix = "https://islas27.github.io"
